version: 2
jobs:
  build:
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run:
          name: setup env
          command: |  # use pipenv to install dependencies
            pip install "poetry>=0.12"
            poetry install
      - run:
          name: run tests
          command: |
            poetry run python -m unittest discover -v