version: 2
jobs:
  build:
    docker:
      - image: python:3.7-slim
    steps:
      - checkout
      - run:
          name: setup env
          command: |  # use pipenv to install dependencies
            pip install "poetry>=0.12"
            poetry config settings.virtualenvs.in-project true
            poetry install
      - run:
          name: Running tests
          command: |
            python -m unittest discover