athena:
  read_write_access: false

run_glue_job:
  iam_role: iam_role_name

read_only_s3_access:
  - test_bucket_read_only/*

read_write_s3_access:
  - test_bucket_read_write/*
  - test_bucket_read_only/write_folder/*