iam_role_name: iam_role_name

athena:
  write: false
  dump_bucket:
    - mojap-athena-query-dump

glue_job: true

secrets: true

s3:
  read_only:
    - test_bucket_read_only/*

  write_only:
    - test_bucket_write_only/*
    - test_bucket_read_only/write_only_folder/*

  read_write:
    - test_bucket_read_write/*
    - test_bucket_read_only/write_folder/*

  deny:
    - test_bucket_read_write/sensitive_table
