name: Lint Python
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v2
      - name: Python linting
        uses: moj-analytical-services/actions-lint-python@main
        with:
          python-version: ${{ matrix.python-version }}
