name: Lint
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Python linting
        uses: moj-analytical-services/actions-lint-python@docker_version
      - name: YAML linting
        uses: moj-analytical-services/actions-lint-yaml@docker_version
