name: Lint YAML
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: YAML linting
        uses: moj-analytical-services/actions-lint-yaml@main
